### ISSUE TITLE
link shortener?

### ISSUE THREAD

**Issue by reecepbcups** [Reecepbcups/cw-webhost#6]
compress a URL redirect into a simple hash. use (uploader + block + url) shasum[:] of some amount of bytes

then allow that on all of Juno, auto redirect through server

**Comment by theghostmac** [comment]
Could use a little more info on this part: "then allow that on all of Juno, auto redirect through server." But started a PR already.

**Comment by reecepbcups** [comment]
That part would be module side for the redirection through any rest api endpoint (like the actual 301 process). 

> then allow that on all of Juno, auto redirect through server

is not done contract side
